<?php
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    ini_set('error_reporting', E_ALL);
    define('BASE_PATH', $_SERVER['DOCUMENT_ROOT']);
    define('ROOT', BASE_PATH . '/1perfectchoice/');
    define('SCRIPT_ROOT', BASE_PATH . '/1perfectchoice/script/');
    define('IMG', ROOT . 'images/');
    define('DOWNLOAD', ROOT . 'download/');
    define('UPLOAD', ROOT . 'upload/');
    define('INVENTORY', ROOT . 'inventory/');
    define('FILTER', ROOT . 'filter/');
    define('LOG', ROOT . 'log/');
    define('LOG_FILE', ROOT . 'log/1perfectchoice.log');
    define('MAX_UPLOAD_SIZE', 1000000);
    define('TEST_NUMBER', 1000);
    define('BRAND', 'Simple Relax');
    define('UPS_DIMENSION_WEIGHT_DIVIDER', 166);
    define('UPS_WEIGHT_LIMIT', 150);
    define('UPS_MEASUREMENT_LIMIT', 165);
    define('UPS_LENGTH_LIMIT', 108);
    define('UPS_FUEL_SURCHARGE', 6.75);
    define('UPS_LARGE_PACKAGE_LIMIT', 130);
    define('UPS_LARGE_PACKAGE_COST', 70);
    define('UPS_INSURANCE_RATE', 4.5);
    define('UPS_BASE_INSURANCE_COST', 9);
    define('UPS_BASE_INSURANCE_COVERAGE', 300);
    define('TRUCKING_BASE_COST', 375);
    define('TRUCKING_BASE_WEIGHT', 250);
    define('TRUCKING_RATE', 1.5);
    define('MAX_CUFT_ON_PALLET', 80);
    define('ONE_DAY_IN_SECONDS', 86400); // 24 * 60 * 60 = 86400 = 1 Day
    define('DB_SERVER', '127.0.0.1');
    define('DB_USER', 'root');
    define('DB_PASS', '');
    define('FTP_SERVER', '3pxusa.com');
    define('FTP_USER', 'aaron@3pxusa.com');
    define('FTP_PASS', 'c7w2l181');
    define('DATABASE', '1perfectchoice');
    define('IMAGE_SERVER', 'https://mail.3pxusa.com/images/');
?>
